apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebapp
  labels:
    environment: demo
    app: samplewebapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: samplewebapp
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: samplewebapp
    spec:
      containers:
      - image: '${#stage("Jenkins")["context"]["IMAGE_NAME"]}'
        imagePullPolicy: Always
        name: samplewebapp
        ports:
        - containerPort: 8080
