apiVersion: v1
kind: Service
metadata:
  name: samplewebapp
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: samplewebapp
